### ISSUE TITLE
Nodes are automatically created according to MPI amounts？

### ISSUE THREAD

**Issue by iniwap** [golosio/NeuronGPU#4]
like pynest，can NeuronGPU support this?（memory waste heavily）

**Comment by golosio** [comment]
No, the current version does not support this. The user must decide in advance  how nodes are distributed among MPI processes. Also consider that NeuronGPU MPI functions are not documented yet. We made several tests and the MPI implementation works well, but it is a relatively new feature.

**Comment by iniwap** [comment]
(Potjans_2014)  "mpirun -np 8 python3 run_microcircuit.py"，on single machine with 2 GPUs，it will crash or process killed，does this mean that equal or more GPUs are required?

another question，whether multi-GPU is supported？

**Comment by golosio** [comment]
This implementation of the Potjans-Diesmann model in not designed for running through MPI, therefore the script is not intended to be executed by mpirun. The README file in the Potjans_2014 folder clearly specify how to run the script. 
Currently multi-GPU is not supported, it can be obtained only through MPI by running on each host a number of MPI processes equal to the number of GPU devices on that host, and in each MPI process taking care of selecting the proper GPU device.
As I said, the problem is that MPI usage is not yet documented. I'm opening a separate issue about this problem.
